### ISSUE TITLE
icecream cannot print out a named list

### ISSUE THREAD

**Issue by rocke2020** [lewinfox/icecream#20]
library(icecream)
r
```
a <- list(name = 0.8, name2 = 0.9)
ic(a[1])
print(a[1])
ic(a)
print(a)
```

I used icecreame 0.2 and R 4.2.2, the print results are below. 
Could we print out the contents in named list? 
thanks!!

ℹ ic| `a[1]`: list [1]: $'name': dbl [1]
$name
[1] 0.8

ℹ ic| `a`: list [2]: $'name': dbl [1], $'name2': dbl [1]
$name
[1] 0.8

$name2
[1] 0.9

**Comment by rocke2020** [comment]
is it a known limit? Or I have sth wrong?
thanks!!

**Comment by lewinfox** [comment]
Hi @rocke2020, thank you for your interest in the project. Could you show what you think the output should look like?

Running your code I get the same output, which looks correct to me.

``` r
a <- list(name = 0.8, name2 = 0.9)

ic(a[1])
#> ℹ ic| `a[1]`: list [1]: $'name': dbl [1]

ic(a)
#> ℹ ic| `a`: list [2]: $'name': dbl [1], $'name2': dbl [1]

print(a)
#> $name
#> [1] 0.8
#>
#> $name2
#> [1] 0.9

```

If you're wondering why the the output of `ic()` is different to `print()`, yes that's deliberate. We avoid printing objects on multiple lines in order to keep console output clean.

For example, this is how we display a 100-element list:

``` r
> ic(rep(list(1), 100))
#> ℹ ic| `rep(list(1), 100)`: list [100]: $1: dbl [1], $2: dbl [1], $3: dbl [1], $4: dbl [1], $5: dbl [1], $6: dbl [1], $7: dbl [1], ...
```

And a data frame:

``` r
ic(iris)
#> ℹ ic| `iris`: data.frame [150 x 5]: $'Sepal.Length': dbl [150], $'Sepal.Width': dbl [150], $'Petal.Length': dbl [150], ...
```

Note that we have printed as much as we can on a single line and then truncated it with `...`.

If I've misunderstood your question please let me know!

**Comment by lewinfox** [comment]
Hi @rocke2020 - if the above hasn't addressed your issue please let me know, otherwise I'm going to close this. Thanks!
